# Generated by Django 5.2.8 on 2025-11-16 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Ex: Étude d'Impact, Analyses", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de Projet',
                'verbose_name_plural': 'Catégories de Projet',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(help_text='Logo du client (sera affiché en grayscale)', upload_to='client_logos/')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('est_active', models.BooleanField(default=False, help_text='Cochez pour que cette question soit ouverte par défaut (une seule recommandée)')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Question (FAQ)',
                'verbose_name_plural': 'Questions (FAQ)',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='HeroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(help_text="Nom de l'icône Bootstrap (ex: 'bi bi-flask')", max_length=50)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature (Accueil)',
                'verbose_name_plural': 'Features (Accueil)',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(help_text="Ex: 'Directeur Scientifique'", max_length=200)),
                ('description', models.TextField(help_text='Courte biographie du membre.')),
                ('image', models.ImageField(help_text='Photo du membre (de préférence carrée ou ratio 1/1.1)', upload_to='equipe/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Pour trier l'affichage (le plus petit en premier).")),
                ('lien_twitter', models.URLField(blank=True, help_text='Lien complet (URL) vers le profil Twitter/X')),
                ('lien_linkedin', models.URLField(blank=True, help_text='Lien complet (URL) vers le profil LinkedIn')),
                ('email', models.EmailField(blank=True, help_text='Adresse email publique (optionnel)', max_length=254)),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_titre', models.CharField(default='Notre mission', max_length=200)),
                ('mission_texte', models.TextField(blank=True, help_text="Le paragraphe principal sous 'Notre mission'")),
                ('vision_titre', models.CharField(default='Notre vision', max_length=200)),
                ('vision_texte', models.TextField(blank=True)),
                ('equipe_titre', models.CharField(default='Notre équipe', max_length=200)),
                ('equipe_texte', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text="L'image principale de la page À Propos", null=True, upload_to='about_page/')),
                ('image_overlay_titre', models.CharField(default='Professionnalisme & Rigueur', max_length=100)),
                ('image_overlay_texte', models.CharField(default='Des solutions durables et performantes', max_length=200)),
            ],
            options={
                'verbose_name': 'Page À Propos',
                'verbose_name_plural': 'Page À Propos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(help_text="Nom de l'icône Bootstrap (ex: 'bi bi-tree')", max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Courte description du service.')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Pour trier l'affichage (le plus petit en premier).")),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('hero', 'Carte Flottante Hero'), ('stats', 'Section Chiffres Clés')], default='stats', max_length=10)),
                ('valeur', models.CharField(help_text="La valeur (ex: '2025' ou '7+')", max_length=20)),
                ('label', models.CharField(help_text="Le titre (ex: 'Année de création')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Courte description (pour la section Stats)', null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="Ex: 'Responsable Environnement, Entreprise Agro'", max_length=100)),
                ('texte', models.TextField(help_text='Le contenu du témoignage')),
                ('image', models.ImageField(upload_to='testimonial_photos/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Note de 1 à 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.TextField(help_text='La description courte sous le titre (sur la page détail)')),
                ('image_principale', models.ImageField(help_text='Image affichée sur la page de liste (galerie)', upload_to='projets/miniatures/')),
                ('client', models.CharField(blank=True, max_length=200)),
                ('duree', models.CharField(blank=True, help_text="Ex: '6 mois'", max_length=100)),
                ('annee', models.PositiveIntegerField(default=2025)),
                ('services_utilises', models.CharField(blank=True, help_text="Ex: 'Étude d'Impact, Analyses, Conseil'", max_length=200)),
                ('apercu_projet', models.TextField(blank=True, help_text="Le texte dans 'Aperçu du Projet'")),
                ('le_defi', models.TextField(blank=True, help_text="Le texte dans 'Le Défi'")),
                ('notre_approche', models.TextField(blank=True, help_text="Le texte dans 'Notre Approche'")),
                ('impact_resultats_texte', models.TextField(blank=True, help_text="Le petit paragraphe 'Impact & Results'")),
                ('points_cles_description', models.TextField(blank=True, help_text="La description sous 'Points Clés du Projet'")),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorieprojet')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-annee', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='PointCleProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(default='bi bi-clipboard-data', help_text="Nom de l'icône Bootstrap", max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_cles', to='core.projet')),
            ],
            options={
                'verbose_name': 'Point Clé',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='OutilTechnologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(help_text="Ex: 'Analyses & Mesures', 'Modélisation'", max_length=100)),
                ('nom', models.CharField(help_text="Ex: 'Chromatographie', 'SIG'", max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outils', to='core.projet')),
            ],
            options={
                'verbose_name': 'Outil/Technologie',
                'ordering': ['categorie', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='MetriqueProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text="Ex: '85%' ou '500+'", max_length=50)),
                ('label', models.CharField(help_text="Ex: 'Réduction des impacts'", max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metriques', to='core.projet')),
            ],
            options={
                'verbose_name': 'Métrique',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ImageSliderProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/slider/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_slider', to='core.projet')),
            ],
            options={
                'verbose_name': 'Image du Slider',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ImageProcessusProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projets/processus/')),
                ('legende', models.CharField(max_length=200)),
                ('est_large', models.BooleanField(default=False, help_text="Cochez si cette image doit être plus grande (style 'large')")),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_processus', to='core.projet')),
            ],
            options={
                'verbose_name': 'Image de Processus',
                'ordering': ['ordre'],
            },
        ),
    ]
