# Generated by Django 5.2.8 on 2026-01-11 17:53

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(help_text='Logo du client (sera affiché en grayscale)', storage=core.storage_backends.SupabaseStorage(), upload_to='client_logos/'),
        ),
        migrations.AlterField(
            model_name='herofeature',
            name='icone',
            field=models.ImageField(help_text='Upload une image (PNG, SVG, JPG) qui sera affichée en blanc sur fond vert.', storage=core.storage_backends.SupabaseStorage(), upload_to='hero_features/', verbose_name='Icône / Image'),
        ),
        migrations.AlterField(
            model_name='imageprocessusprojet',
            name='image',
            field=models.ImageField(storage=core.storage_backends.SupabaseStorage(), upload_to='projets/processus/'),
        ),
        migrations.AlterField(
            model_name='imagesliderprojet',
            name='image',
            field=models.ImageField(storage=core.storage_backends.SupabaseStorage(), upload_to='projets/slider/'),
        ),
        migrations.AlterField(
            model_name='membreequipe',
            name='image',
            field=models.ImageField(help_text='Photo du membre (de préférence carrée ou ratio 1/1.1)', storage=core.storage_backends.SupabaseStorage(), upload_to='equipe/'),
        ),
        migrations.AlterField(
            model_name='pageabout',
            name='image',
            field=models.ImageField(blank=True, help_text="L'image principale de la page À Propos", null=True, storage=core.storage_backends.SupabaseStorage(), upload_to='about_page/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_principale',
            field=models.ImageField(help_text='Image affichée sur la page de liste (galerie)', storage=core.storage_backends.SupabaseStorage(), upload_to='projets/miniatures/'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.SupabaseStorage(), upload_to='testimonial_photos/'),
        ),
    ]
